"""Generate reports/day1_validation_report.md from live computations.

Every number in the report is computed by this script, nothing is typed by hand.
Run:  python scripts/make_validation_report.py
"""
import calendar
import platform
import random
import subprocess
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "tests"))

import numpy as np
import QuantLib as ql

from credit_engine.pricing.bond import Bond, clean_price, dirty_price
from credit_engine.pricing.daycount import DayCount
from credit_engine.pricing.yield_solver import ytm_brent, ytm_newton
from credit_engine.risk.duration import (convexity, dv01, effective_convexity,
                                         effective_duration, macaulay_duration,
                                         modified_duration)
from test_vs_quantlib import _ql_metrics, _random_case, _touches_feb_eom

out = []
w = out.append

# ---------------------------------------------------------------- test suite
res = subprocess.run([sys.executable, "-m", "pytest", "-q", str(ROOT)], capture_output=True, text=True)
summary = res.stdout.strip().splitlines()[-1]

w("# Day 1 validation report\n")
w(f"*Generated by `scripts/make_validation_report.py`. Python {platform.python_version()}, "
  f"QuantLib {ql.__version__}, numpy {np.__version__}.*\n")
w(f"**Test suite:** `{summary}`\n")

# --------------------------------------------------------------- hand example
b = Bond(0.05, date(2027, 1, 15), frequency=1)
s = date(2025, 1, 15)
hand = {"Dirty price": (100.0, dirty_price(b, s, 0.05)),
        "Macaulay duration": (1.952381, macaulay_duration(b, s, 0.05)),
        "Modified duration": (1.859410, modified_duration(b, s, 0.05)),
        "Convexity": (5.269409, convexity(b, s, 0.05)),
        "DV01 (per 100 par)": (0.018594, dv01(b, s, 0.05))}
w("## 1. Hand calculation (2y, 5% annual coupon, YTM 5%, settle on coupon date)\n")
w("| Metric | By hand | Code |\n|---|---:|---:|")
for k, (h, c) in hand.items():
    w(f"| {k} | {h:.6f} | {c:.6f} |")
w("")

# ------------------------------------------------- analytic vs bump-and-reprice
w("## 2. Analytic vs bump-and-reprice (1bp central difference)\n")
w("| Bond | ModD analytic | ModD bump | Conv analytic | Conv bump |\n|---|---:|---:|---:|---:|")
for label, bond, st, y in [
    ("5% 2032, y=4.5%", Bond(0.05, date(2032, 3, 1)), date(2026, 5, 20), 0.045),
    ("8.5% 2029 (HY), y=10%", Bond(0.085, date(2029, 11, 15)), date(2026, 1, 3), 0.10),
    ("3% 2056 annual, y=5.5%", Bond(0.03, date(2056, 8, 31), 1), date(2026, 2, 10), 0.055),
]:
    w(f"| {label} | {modified_duration(bond, st, y):.6f} | {effective_duration(bond, st, y):.6f} | "
      f"{convexity(bond, st, y):.4f} | {effective_convexity(bond, st, y):.4f} |")
w("")

# ------------------------------------------------------ sample bonds vs QuantLib
w("## 3. Sample bonds vs QuantLib\n")
samples = [
    ("BBB-like 10y 30/360", Bond(0.058, date(2036, 9, 15)), date(2026, 9, 21), 0.057),
    ("HY-like 7y 30/360", Bond(0.085, date(2033, 9, 15)), date(2026, 9, 21), 0.087),
    ("AAA-like 5y ACT/ACT", Bond(0.045, date(2031, 9, 15), 2, DayCount.ACT_ACT_ICMA), date(2026, 9, 21), 0.048),
]
w("| Bond | Metric | Ours | QuantLib | Abs diff |\n|---|---|---:|---:|---:|")
for label, bond, st, y in samples:
    q = _ql_metrics(bond, st, y)
    ours = {"Clean price": clean_price(bond, st, y), "Accrued": bond.accrued_interest(st),
            "Macaulay": macaulay_duration(bond, st, y), "Modified": modified_duration(bond, st, y),
            "Convexity": convexity(bond, st, y), "DV01 /100": dv01(bond, st, y)}
    theirs = {"Clean price": q["clean"], "Accrued": q["accrued"], "Macaulay": q["macaulay"],
              "Modified": q["modified"], "Convexity": q["convexity"], "DV01 /100": q["dv01"]}
    for k in ours:
        w(f"| {label} | {k} | {ours[k]:.8f} | {theirs[k]:.8f} | {abs(ours[k]-theirs[k]):.1e} |")
w("")

# ------------------------------------------------------- 300 random bonds
w("## 4. 300 random bonds vs QuantLib (maximum error over all cases)\n")
w("| Day count | Cases | Price | Accrued | Macaulay (rel) | Modified (rel) | Convexity (rel) | Yield (bp) |\n|---|---:|---:|---:|---:|---:|---:|---:|")
feb_stats = None
for dc in (DayCount.THIRTY_360, DayCount.ACT_ACT_ICMA):
    rng = random.Random(42)
    m = dict(p=0, a=0, mac=0, mod=0, cv=0, y=0)
    n = 0
    feb = []
    for _ in range(300):
        bond, st, y = _random_case(rng, dc)
        q = _ql_metrics(bond, st, y)
        if dc is DayCount.THIRTY_360 and _touches_feb_eom(bond, st):
            feb.append(abs(ytm_brent(bond, st, q["clean"]) - y) * 1e4)
            continue
        n += 1
        m["p"] = max(m["p"], abs(dirty_price(bond, st, y) - q["dirty"]))
        m["a"] = max(m["a"], abs(bond.accrued_interest(st) - q["accrued"]))
        m["mac"] = max(m["mac"], abs(macaulay_duration(bond, st, y) / q["macaulay"] - 1))
        m["mod"] = max(m["mod"], abs(modified_duration(bond, st, y) / q["modified"] - 1))
        m["cv"] = max(m["cv"], abs(convexity(bond, st, y) / q["convexity"] - 1))
        m["y"] = max(m["y"], abs(ytm_brent(bond, st, q["clean"]) - y) * 1e4,
                     abs(ytm_newton(bond, st, q["clean"]) - y) * 1e4)
    if feb:
        feb_stats = (len(feb), float(np.median(feb)), max(feb))
    label = f"{dc.value}" + (" (excl. Feb-EOM)" if dc is DayCount.THIRTY_360 else "")
    w(f"| {label} | {n} | {m['p']:.1e} | {m['a']:.1e} | {m['mac']:.1e} | {m['mod']:.1e} | {m['cv']:.1e} | {m['y']:.1e} |")
w("")
if feb_stats:
    w("## 5. Known limitation: 30/360 with a February end-of-month coupon date\n")
    w(f"{feb_stats[0]} of 300 random 30/360 cases involve a Feb end-of-month coupon or settlement. "
      f"Implied-yield difference vs QuantLib: median {feb_stats[1]:.2f} bp, max {feb_stats[2]:.2f} bp. "
      "Not resolved which convention a given market data vendor uses; ACT/ACT is unaffected.\n")

Path(ROOT / "reports").mkdir(exist_ok=True)
(ROOT / "reports" / "day1_validation_report.md").write_text("\n".join(out))
print("\n".join(out))
